#include<iostream>
using namespace std;
void quickSort(int a[], int first, int last);
int pivot(int a[], int first, int last);
void swap(int& a, int& b);
void swapNoTemp(int& a, int& b);
void print(int array[], const int& N);
int main_quicksort();
int main_hashmap();
int main_template();
int main_smartptr();
int main_linkedlist();
int main_nbn();
int main_permu();
int main_inter();
int main_dtor();
int main_palin();
int main_strspaces();
int main_logic();
int main_vdtor();
int main_weakptr();
int main_4greatest();
int main_ambi(int argc, char *argv[]); 
int main_templatetest();
int main_transform();
int main_maperase();
int main_dctors();
int main_constcast();
int main_staticbinding();
int main_dfltctor();
int main_reverseint();
int main_infixtopostfix();
int main_privateInheritance();
int main_find_most_occuring_char();
int main_number_words();
int main_access_private();
int main_iterator_demo();
int main_weak_ptr_demo();
int main_stl_ctor();
int main_bst();
int main_scoped_ptr_demo();
int main_dll_checkpalin();